# Generated by Django 3.1.4 on 2021-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_auto_20210926_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='apiApp.BlogImages'),
        ),
    ]
