# Generated by Django 3.1.4 on 2021-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_auto_20210926_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.ManyToManyField(blank=True, null=True, to='apiApp.Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='apiApp.SubCategory'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='apiApp.Tags'),
        ),
    ]
