# Generated by Django 3.2.7 on 2021-10-23 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_auto_20210926_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('timestamped_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.timestamped')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
            bases=('apiApp.timestamped',),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('timestamped_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.timestamped')),
                ('video_name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(upload_to='video/')),
                ('link', models.URLField(max_length=400)),
                ('duration', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 7, 49, 50, 632615))),
            ],
            bases=('apiApp.timestamped',),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('timestamped_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiApp.timestamped')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(upload_to='course/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.ManyToManyField(to='apiApp.Testimonial')),
                ('video', models.ManyToManyField(to='apiApp.Videos')),
            ],
            bases=('apiApp.timestamped',),
        ),
    ]
